food/urls.py
from . import views #.means current dir
from django.urls import path

app_name='food'
urlpatterns =[
    path('',views.index,name='index'),
    path('<int:pk>/',views.FoodDetail.as_view(),name='detail'),
    path('add',views.CreateItem.as_view(),name='create_item'),
    path('update/<int:id>',views.update_item,name='update_item'),
    path('delete/<int:id>',views.delete_item,name='delete_item'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include,path
from users import views as user_views
from django.contrib.auth import views as authentication_views
from . import views as mysite_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',mysite_views.home,name='home'),
    path('food/',include('food.urls')),
    path('register/',user_views.register,name='register'),
    path('login/',authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', mysite_views.CustomLogoutView.as_view(), name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
]

urlpatterns += [
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):

    def __str__(self):
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default="https://cdn3.iconfinder.com/data/icons/food-delivery-60/24/order_process_loading_food_menu_nonstop_service-512.png")

    def get_absolute_url(self):
        return reverse("food:detail",kwargs={"pk":self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields = ['item_name','item_desc','item_price','item_image']
        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField

    class Meta:
        model = User
        fields=['username','email','password1','password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render,redirect
from .models import Item
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# Create your views here.
def index(request):
    item_list = Item.objects.all()

    name=request.GET.get('name')
    if name!='' and name is not None:
        item_list=item_list.filter(item_name__icontains=name)

    paginator=Paginator(item_list,5)
    page=request.GET.get('page')
    item_list=paginator.get_page(page)
    return render(request, 'food/index.html', {'item_list': item_list})

class FoodDetail(DetailView):
    model=Item
    template_name='food/detail.html'
    context_object_name='item'

class CreateItem(CreateView):
    model = Item
    fields=['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'

    def form_valid(self,form):
        form.instance.user_name=self.request.user
        return super().form_valid(form)

@login_required
def update_item(request,id):
    item = Item.objects.get(pk=id)
    form = ItemForm(request.POST or None,instance=item)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form,'item':item})

@login_required
def delete_item(request,id):
    item = Item.objects.get(pk=id)
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/item-delete.html',{'item':item})

mysite/views.py
from django.contrib.auth import logout
from django.shortcuts import render
from django.views.generic import View
from django.contrib import messages
def home(request):
    return render(request,'users/home.html')

class CustomLogoutView(View):
    def get(self, request):
        logout(request)
        messages.success(request,f'You have been logged out')
        return render(request,'users/home.html')

    def post(self, request):
        logout(request)
        messages.success(request,f'You have been logged out')
        return render(request,'users/home.html')

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from .forms import RegisterForm
from django.contrib.auth.decorators import login_required
# Create your views here.
def register(request):
    if request.method == 'POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username=form.cleaned_data.get('username')
            messages.success(request,f'Welcome {username}, your account has been created')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'users/register.html',{'form':form})

@login_required
def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="{% url 'food:index' %}" class="navbar-brand ms-3">Food App</a>
        <div class="navbar">
            {% if user.is_authenticated %}
                <a class="nav-item nav-link text-light me-3" href="{% url 'food:create_item' %}">Add Item</a>
            {% else %}
                <a class="nav-item nav-link text-light me-3" href="{% url 'login' %}">Add Item</a>
            {% endif %}
            {% if user.is_authenticated %}
            <a href="{% url 'logout' %}" class="nav-item nav-link text-light me-3">Logout</a>
            <a href="{% url 'profile' %}" class="nav-item nav-link text-light">Profile</a>
            {% else %}
            <a href="{% url 'login' %}" class="nav-item nav-link text-light">Login</a>
            {% endif %}
        </div>
    </nav>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{message}}</div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img width="350px" src="{{ item.item_image }}" alt="Image not found" class="card"/>
        </div>
        <div class="col-md-8">
            <h1>Name: {{ item.item_name }}</h1>
            <h2>Description: {{ item.item_desc }}</h2>
            <h3>Price: Rs. {{ item.item_price }}</h3>
            <br>
            <h6>Added by: {{ item.user_name }}</h6>
            <a href="{% url 'food:update_item' item.id %}">Update</a>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>List</title>
    <style>
        .NoItem {
            text-align: center;
            margin-top: 20px;
            padding: 10px;
            background-color: #f8d7da;
            border: 1px solid #f5c6cb;
            border-radius: 5px;
        }
    </style>
</head>
<body>
    {% block body %}
    <div class="SearchBar">
        <form action="" method="GET">
            <input type="search" name="name" placeholder="Search...">
            <button type="submit">Search</button>
        </form>
    </div>
    {% if item_list %}
        {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="200px" width="200px" src="{{item.item_image}}">
            </div>
            <div class="col-md-4">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>Rs. {{ item.item_price }}</h6>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        {% endfor %}
        <div class="paginator">
            {% if item_list.has_previous %}
                <a href="?page=1">First</a>
                <a href="?page={{ item_list.previous_page_number }}">Previous</a>
            {% endif %}

            Page:{{ item_list.number }} of {{ item_list.paginator.num_pages }}

            {% if item_list.has_next %}
                <a href="?page={{ item_list.next_page_number }}">Next</a>
                <a href="?page={{ item_list.paginatior.num_pages }}">Last</a>
            {% endif %}
        </div>
    {% else %}
        <div class="NoItem">
            <h5 style="text-align: center;">No food items available.</h5>
        </div>
    {% endif %}
    {% endblock %}
</body>
</html>

food/templates/food/item-delete.html
<style>
    form {
        text-align: center;
        margin-top: 20px;
    }

    h2 {
        color: #333;
    }

    button {
        padding: 10px 20px;
        margin: 0 10px;
        cursor: pointer;
        border: none;
        border-radius: 5px;
    }

    button[type="submit"] {
        background-color: #4CAF50;
        color: white;
    }

    button[type="button"] {
        background-color: #ccc;
        color: #333;
    }
</style>

<form method="POST" id="deleteForm">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
    <button type="button" onclick="cancelDelete()">Cancel</button>
</form>

<script>
    function cancelDelete() {
        // Redirect to the specified URL
        window.location.href = '{% url "food:index" %}';
    }
</script>

food/templates/food/item-form.html
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin-top: 50px;
    }

    form {
        max-width: 400px;
        margin: 0 auto;
        background-color: #ffffff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
        text-align: left;
        position: relative;
    }

    .form-title {
        background-color: #092e47;
        text-align: center;
        font-weight: bold;
        color: #ffffff;
        padding: 5px;
        border-radius: 8px; /* Adjust the border-radius for rounded corners */
    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
        color: #333;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #3498db;
        color: #ffffff;
        padding: 10px 15px; /* Decreased padding */
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #2980b9;
    }
</style>

{% extends 'food/base.html' %}
{% block body %}
<form method="post">
    <div class="form-title">
        <h3>Add Item</h3>
    </div>
    {% csrf_token %}
    {{ form }}
    <button type="Submit">Save</button>
</form>
{% endblock %}

users/templates/users/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Food App</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f4;
            text-align: center;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 600px;
            margin: 50px auto;
        }

        .button-container {
            display: flex;
            flex-direction: column;
            margin-top: 30px;
        }

        .button {
            display: block;
            width: 150px;
            padding: 15px;
            margin: 10px auto;
            text-decoration: none;
            color: #fff;
            font-weight: bold;
            border-radius: 5px;
            text-align: center;
            transition: background-color 0.3s;
        }

        .button:nth-child(1) {
            background-color: #3498db;
        }

        .button:nth-child(2) {
            background-color: #e74c3c;
        }

        .link {
            display: block;
            width: 100%;
            margin: 10px auto;
            text-decoration: none;
            color: #3498db;
            font-weight: bold;
            text-align: center;
        }
    </style>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">{{message}}</div>
        {% endfor %}
    {% endif %}
    <div class="container">
        <h1>Food App</h1>
        <p>Made with Django!</p>
        <div class="button-container">
            <a class="button" href="{% url 'login' %}">Login</a>
            <a class="button" href="{% url 'register' %}">Register</a>
            <a class="link" href="{% url 'food:index' %}">Continue without login</a>
        </div>
    </div>
</body>
</html>

users/templates/users/login.html
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin-top: 50px;
    }

    .form-title {
        background-color: #114305;
        text-align: center;
        font-weight: bold;
        color: #ffffff;
        padding: 5px;
        border-radius: 8px;
    }

    form {
        max-width: 300px;
        margin: 0 auto;
        background-color: #ffffff;
        padding: 30px;
        border-radius: 8px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
        text-align: left;
    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
        color: #333;
    }

    input {
        width: 100%;
        padding: 12px;
        margin-bottom: 20px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #4caf50;
        color: #ffffff;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #45a049;
    }
</style>

<form method="POST">
    <div class="form-title">
        <h3>Login</h3>
    </div>
    {% csrf_token %}
    {{ form }}
    <button type="submit">Login</button>
</form>

users/templates/users/profile.html
{% extends 'food/base.html' %}
{% block body %}
<h1>{{ user.username }}</h1>
<img src="{{ user.profile.image.url }}" height="300px" width="300px">
{% endblock %}

users/templates/users/register.html
<style>
    body {
        font-family: 'Arial', sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        margin-top: 50px;
    }

    .form-title {
        background-color: #073452;
        text-align: center;
        font-weight: bold;
        color: #ffffff;
        padding: 10px;
        border-radius: 8px;
    }

    form {
        max-width: 500px;
        margin: 0 auto;
        background-color: #ffffff;
        padding: 20px;
        border-radius: 8px;
        box-shadow: 0 0 15px rgba(0, 0, 0, 0.2);
        text-align: left;
    }

    label {
        display: block;
        margin-bottom: 10px;
        font-weight: bold;
        color: #333;
    }

    input {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        box-sizing: border-box;
        border: 1px solid #ccc;
        border-radius: 4px;
    }

    button {
        background-color: #3498db;
        color: #ffffff;
        padding: 10px 15px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s;
    }

    button:hover {
        background-color: #2980b9;
    }
</style>
<form method="post">
    {% csrf_token %}
    <div class="form-title">
        <h3>Register</h3>
    </div>
    {{ form }}
    <button type="submit">Sign Up!</button>
</form>